### PR TITLE
Restrict `ArrowTypes.JuliaType` to `S3Path{Nothing}` to make type fully concrete

### LINKED ISSUE #263: ArrowTypes support for S3Path fails with `missing` values
```
julia> using AWSS3, DataFrames, Arrow

julia> tbl = (; path = [S3Path("s3://blah/argh/stuff"), S3Path("s3://blah/something"), missing])
(path = Union{Missing, S3Path{Nothing}}[p"s3://blah/argh/stuff", p"s3://blah/something", missing],)

julia> tbl2 = Arrow.Table(Arrow.tobuffer(tbl))
Arrow.Table with 3 rows, 1 columns, and schema:
 :path  Union{Missing, S3Path}

julia> tbl2.path
3-element Arrow.List{Union{Missing, S3Path}, Int32, Vector{UInt8}}:
Error showing value of type Arrow.List{Union{Missing, S3Path}, Int32, Vector{UInt8}}:
ERROR: MethodError: no method matching Union{Missing, S3Path}(::String)
Stacktrace:
  [1] fromarrow(#unused#::Type{Union{Missing, S3Path}}, x::String)
    @ ArrowTypes ~/.julia/packages/ArrowTypes/dkiHE/src/ArrowTypes.jl:157
  [2] fromarrow(#unused#::Type{Union{Missing, S3Path}}, ptr::Ptr{UInt8}, len::Int64)
    @ ArrowTypes ~/.julia/packages/ArrowTypes/dkiHE/src/ArrowTypes.jl:201
  [3] getindex
    @ ~/.julia/packages/Arrow/ZlMFU/src/arraytypes/list.jl:54 [inlined]
```

For some reason, the methods for `S3Path` are not being hit here.  I'm not familiar enough with the internals of Arrow to understand whether this is expected or not.

### PR DESCRIPTION
**Pull request by kleinschmidt**
This fixes #263 by restricting the type that is returned by `JuliaType` to be fully concrete.

### CODE REVIEW

**Review by ericphanson — APPROVED** [review]
Bump patch version?

bors try

File: src/s3path.jl [hunk 1]
```diff
@@ -656,7 +656,7 @@ end
 const S3PATH_ARROW_NAME = Symbol("JuliaLang.AWSS3.S3Path")
 ArrowTypes.arrowname(::Type{<:S3Path}) = S3PATH_ARROW_NAME
 ArrowTypes.ArrowType(::Type{<:S3Path}) = String
-ArrowTypes.JuliaType(::Val{S3PATH_ARROW_NAME}, ::Any) = S3Path
+ArrowTypes.JuliaType(::Val{S3PATH_ARROW_NAME}, ::Any) = S3Path{Nothing}
 ArrowTypes.fromarrow(::Type{<:S3Path}, uri_string) = S3Path(uri_string)
```
Comment (ericphanson) [inline src/s3path.jl:660]: maybe?
```suggestion
ArrowTypes.fromarrow(::Type{<:S3Path}, uri_string) = S3Path{Nothing}(uri_string)
```

Comment (kleinschmidt) [reply src/s3path.jl:660]: I think the error is in the test itself, trying to push a `S3Path{Something}` to a `Vector{Union{S3Path{Nothing}, Missing}}`.  I'll fix...

Comment (kleinschmidt) [reply src/s3path.jl:660]: ready to re-try now.

**Comment by ericphanson** [comment]
bors merge

**Comment by kleinschmidt** [comment]
@ericphanson one more try?

**Comment by ericphanson** [comment]
bors merge

**Comment by kleinschmidt** [comment]
Failure looks unrelated (bucket tagging tiemout on S3)

**Comment by ericphanson** [comment]
bors merge
