### PR TITLE
Fixed issue getting files from root S3 directory

### LINKED ISSUE #60: Most directory operatations do not work on the bucket itself, only on directory with in it
E.g. my bucket has a directory called `images` in it and a file also.
But `readdir` shows nothing
```
julia> using AWSS3, FilePathsBase

julia> readdir(S3Path("s3://oxinaboxpublic/"))
0-element Array{SubString{String},1}

julia> readdir(S3Path("s3://oxinaboxpublic/images/"))
4-element Array{SubString{String},1}:
 "chainloop.svg"
 "chainwithborder.png"
 "chainwithborder.svg"
 "chainwithborder_grey.png"
```

And `sync` fails:
```
julia> sync(S3Path("s3://oxinaboxpublic/images/"), p"out")

julia> readdir(p"out")
4-element Array{String,1}:
 "chainloop.svg"
 "chainwithborder.png"
 "chainwithborder.svg"
 "chainwithborder_grey.png"

julia> mkdir("outall")
"outall"

julia> sync(S3Path("s3://oxinaboxpublic/"), p"outall")
ERROR: ArgumentError: s3://oxinaboxpublic// does not exist
Stacktrace:
 [1] sync(::typeof(FilePathsBase.should_sync), ::S3Path, ::PosixPath; delete::Bool, overwrite::Bool) at /Users/
oxinabox/.julia/packages/FilePathsBase/Oyg1p/src/path.jl:537
 [2] sync at /Users/oxinabox/.julia/packages/FilePathsBase/Oyg1p/src/path.jl:537 [inlined]
 [3] #sync#16 at /Users/oxinabox/.julia/packages/FilePathsBase/Oyg1p/src/path.jl:532 [inlined]
 [4] sync(::S3Path, ::PosixPath) at /Users/oxinabox/.julia/packages/FilePathsBase/Oyg1p/src/path.jl:532
 [5] top-level scope at REPL[16]:1
```

I think something is wrong I guess with how we are interpretting prefixes as directories
Related to #34 maybe

### PR DESCRIPTION
**Pull request by mattBrzezinski**
Resolves #60 

There is a bug with reading files from the root "directory" of an S3 bucket, where when we access the `:key` attribute we would always return back `/` as a prefix. Files cannot be prefixed with this character as it's invalid, and thus we would always return back nothing.

This CR resolves the issue by check if the `fp.segments` are empty, if so return an empty string. `fp.segments` are used for "subdirectories" on an S3 bucket, for instance in the hierarchy below the `segments` for `file.txt` would be `[subdir1, subdir2]`. 

```
bucket-name
|-- subdir1
|     |-- subdir2
|          |-- file.txt
```

I have included testing for both `readdir()` for both S3 and local storage testing. One thing to note with local testing is the difference between an `S3Path` and `AbstractPath`. An `S3Path` will suffix a directory with the `/` character, while an `AbstractPath` will not. This has led to a special case when testing, if anyone has any suggestions on how to improve this I'd love to hear them!

Another thing which I have noticed when using `sync()` if you have two directories consecutively named the same thing, the files in the second directory will not be transferred and you will encounter an error with the `sync()` call. I have logged an issue for this found here: #62 

I have also moved the empty testing buckets code to the end of testing, so that you do not always have 1 bucket of testing data living in S3. I also have logged an issue to refactor testing #61 and just kept the current format going here.

### CODE REVIEW

File: test/issue_60.jl [hunk 1]
```diff
@@ -0,0 +1,60 @@
+@testset "Issue 60" begin
```
Comment (nicoleepp) [inline test/issue_60.jl]: Can this testset and file get a more descriptive name than "issue 60"

File: test/runtests.jl [hunk 2]
```diff
@@ -14,6 +14,7 @@ using HTTP
 using FilePathsBase
 using FilePathsBase.TestPaths
 using LinearAlgebra  # for norm S3Path tests
+using UUIDs
```
Comment (nicoleepp) [inline test/runtests.jl]:
```suggestion
using UUIDs: uuid4
```

File: test/issue_60.jl [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+        @test readdir(path / "subdir1/subdir2/subdir3/") == []
+    end
+
+    initialize()
+
+    @testset "readdir() - S3" begin
+        verify_files(S3Path("s3://$bucket_name/"))
+    end
+
+     @testset "readdir() - Local" begin
```
Comment (nicoleepp) [inline test/issue_60.jl]:
```suggestion
    @testset "readdir() - Local" begin
```

File: test/runtests.jl [hunk 4]
```diff
@@ -290,6 +267,26 @@ versions = s3_list_versions(aws, bucket_name, "key3")
 
 
 include("s3path.jl")
+include("issue_60.jl")
```
Comment (nicoleepp) [inline test/runtests.jl]:
```suggestion
```

**Comment by oxinabox** [comment]
do not forget to bump the version number and tag a release

**Comment by mattBrzezinski** [comment]
Forgot this package doesn't have `bors` setup, I'll leave this until Monday.
